# Generated by Django 3.0.2 on 2020-01-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200116_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
