# Generated by Django 3.0.2 on 2020-01-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200119_0840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
